### ISSUE TITLE
linux-amd64 not working on WSL

### ISSUE THREAD

**Issue by ntratcliff** [itchio/butler#101]
I'm trying to run butler from [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/about), Ubuntu 14.04 (Trusty), but can't seem to get it working. When I run butler, I get the following error:

```
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x82ab13]

goroutine 1 [running, locked to thread]:
runtime.throw(0x9abbb5, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42009bc98 sp=0xc42009bc78
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42009bcf0 sp=0xc42009bc98
github.com/itchio/butler/vendor/github.com/getlantern/stack.findSigpanic.func1(0x0, 0xc42009bd30, 0x0)
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/stack/stack.go:275 +0x53 fp=0xc42009bd18 sp=0xc42009bcf0
github.com/itchio/butler/vendor/github.com/getlantern/stack.findSigpanic(0x9b9581)
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/stack/stack.go:276 +0x3d fp=0xc42009bd48 sp=0xc42009bd18
github.com/itchio/butler/vendor/github.com/getlantern/stack.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/stack/stack.go:280 +0xa7 fp=0xc42009bd78 sp=0xc42009bd48
github.com/itchio/butler/vendor/github.com/getlantern/errors.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/errors/hide.go:51 +0xc1 fp=0xc42009bdf8 sp=0xc42009bd78
github.com/itchio/butler/vendor/github.com/getlantern/golog.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/golog/golog.go:418 +0x85 fp=0xc42009be18 sp=0xc42009bdf8
github.com/itchio/butler/vendor/github.com/getlantern/idletiming.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/getlantern/idletiming/idletiming_listener.go:53 +0x5d fp=0xc42009be48 sp=0xc42009be18
github.com/itchio/butler/vendor/github.com/itchio/httpkit/timeout.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/timeout/timeout.go:44 +0x3d fp=0xc42009be50 sp=0xc42009be48
github.com/itchio/butler/vendor/github.com/itchio/wharf/eos/option.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/eos/option/option.go:47 +0x38 fp=0xc42009be58 sp=0xc42009be50
github.com/itchio/butler/vendor/github.com/itchio/wharf/eos.init()
        /home/amos/builds/630f4286/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/wharf/eos/eos.go:124 +0x71 fp=0xc42009be90 sp=0xc42009be58
main.init()
        github.com/itchio/butler/_obj/_cgo_import.go:5 +0x7b fp=0xc42009bf38 sp=0xc42009be90
runtime.main()
        /usr/local/go/src/runtime/proc.go:172 +0x1bf fp=0xc42009bf90 sp=0xc42009bf38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42009bf98 sp=0xc42009bf90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
```

Any ideas?

**Comment by fasterthanlime** [comment]
Looks like a WSL bug, here's the golang issue that tracks this: https://github.com/golang/go/issues/17365

Changes will need to come either from a Windows update or golang runtime changes, nothing we can do on our side to fix it. (But butler for windows runs great on windows!)

**Comment by ntratcliff** [comment]
Yeah, looks like the issue has been filed with Microsoft as well, and they may have already fixed it in the Insider build: Microsoft/BashOnWindows#1613

Guess I'll just have to stick to butler for Windows until that update hits the stable builds.

**Comment by fasterthanlime** [comment]
Looks like it's fixed! https://github.com/Microsoft/BashOnWindows/issues/1613#issuecomment-275857250
