### ISSUE TITLE
Error when internet access gets cut

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/butler#90]
```
[2016-11-15 @ 14:16:15.088] [butler] butler err: panic: runtime error: invalid memory address or nil pointer dereference
[2016-11-15 @ 14:16:15.088] [butler] butler err: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4282bd6]
[2016-11-15 @ 14:16:15.089] [butler] butler err:
[2016-11-15 @ 14:16:15.089] [butler] butler err: goroutine 1 [running]:
[2016-11-15 @ 14:16:15.089] [butler] butler err: panic(0x4496ca0, 0xc4200161e0)
[2016-11-15 @ 14:16:15.089] [butler] butler err:        /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
[2016-11-15 @ 14:16:15.089] [butler] butler err: github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile.(*httpReader).Close(0xc4203f25f0, 0xc42041be30, 0xc4200c5a78)
[2016-11-15 @ 14:16:15.089] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile/httpfile.go:188 +0x26
[2016-11-15 @ 14:16:15.090] [butler] butler err: github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile.(*HTTPFile).closeAllReaders(0xc420164c00, 0x0, 0x0)
[2016-11-15 @ 14:16:15.090] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile/httpfile.go:524 +0x107
[2016-11-15 @ 14:16:15.090] [butler] butler err: github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile.(*HTTPFile).Close(0xc420164c00, 0x0, 0x0)
[2016-11-15 @ 14:16:15.090] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/vendor/github.com/itchio/httpkit/httpfile/httpfile.go:541 +0x37
[2016-11-15 @ 14:16:15.090] [butler] butler err: main.doCp(0x7fff5fbfd0d1, 0x51, 0x7fff5fbfd123, 0x35, 0xc4200c5d01, 0x47ae5e0, 0xc420320db0)
[2016-11-15 @ 14:16:15.090] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/cp.go:87 +0x605
[2016-11-15 @ 14:16:15.090] [butler] butler err: main.cp(0x7fff5fbfd0d1, 0x51, 0x7fff5fbfd123, 0x35, 0x4515001)
[2016-11-15 @ 14:16:15.090] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/cp.go:16 +0x52
[2016-11-15 @ 14:16:15.090] [butler] butler err: main.main()
[2016-11-15 @ 14:16:15.090] [butler] butler err:        /Users/amos/builds/94518b86/0/itchio/butler/src/github.com/itchio/butler/main.go:449 +0x19d3
```

**Comment by fasterthanlime** [comment]
Fixed by https://github.com/itchio/httpkit/commit/18237439c30bc91ffea543c0a7bb5a960a1a57ac
